[versions]
aws-sdk-version = "2.30.0"
test-allure-bom-version = "2.29.1"
aspectj-version = "1.9.21"
testng-version = "7.9.0"
rest-assured-version = "5.4.0"
apache-commons-version = "3.14.0"
jackson-databind-version = "2.16.1"
secret-manager-version = "2.24.0"
lombok-version = "1.18.30"
jsr310-version = "2.16.1"
jakarta-rs-api-version = "3.1.0"
selenium-version = "4.18.1"
webdrivermanager-version = "6.0.0"
commons-codec-version = "1.15"

[libraries]
# Platform/BOM dependencies
aws-sdk = { module = "software.amazon.awssdk:bom", version.ref = "aws-sdk-version" }
test-allure-bom = { module = "io.qameta.allure:allure-bom", version.ref = "test-allure-bom-version" }

# Core dependencies
aspectj-weaver = { module = "org.aspectj:aspectjweaver", version.ref = "aspectj-version" }
testng = { module = "org.testng:testng", version.ref = "testng-version" }
rest-assured = { module = "io.rest-assured:rest-assured", version.ref = "rest-assured-version" }
apache-commons = { module = "org.apache.commons:commons-lang3", version.ref = "apache-commons-version" }
jackson-databind = { module = "com.fasterxml.jackson.core:jackson-databind", version.ref = "jackson-databind-version" }
secret-manager = { module = "software.amazon.awssdk:secretsmanager", version.ref = "secret-manager-version" }
lombok = { module = "org.projectlombok:lombok", version.ref = "lombok-version" }
jackson-jsr310 = { module = "com.fasterxml.jackson.datatype:jackson-datatype-jsr310", version.ref = "jsr310-version" }
jakarta-rs-api = { module = "jakarta.ws.rs:jakarta.ws.rs-api", version.ref = "jakarta-rs-api-version" }

# Testing dependencies
allure-testng = { module = "io.qameta.allure:allure-testng" }
allure-rest-assured = { module = "io.qameta.allure:allure-rest-assured" }

# Selenium dependencies
selenium-java = { module = "org.seleniumhq.selenium:selenium-java", version.ref = "selenium-version" }
webdrivermanager = { module = "io.github.bonigarcia:webdrivermanager", version.ref = "webdrivermanager-version" }

# Forced dependencies
commons-codec = { module = "commons-codec:commons-codec", version.ref = "commons-codec-version" }